### ISSUE TITLE
部分链接错误；关于头像链接问题

### ISSUE THREAD

**Issue by dabai2017** [Siricee/hexo-theme-Chic#10]
在 文章页面 有一个home按钮。点击之后会404不知道在哪里设置这个地址
在 主页 有一个头像，点击之后不会跳转 归档 页面

**Comment by Siricee** [comment]
> 在 文章页面 有一个home按钮。点击之后会404不知道在哪里设置这个地址

这个问题确实存在，当页面部署到非根目录时会产生这个bug。
**现在该错误已经修正，请重新clone本主题代码部署安装。**
该链接与主配置文件(博客根目录`_config.yml`文件)中的`url`和`root`值有关，请记得填写正确地址。

> 在 主页 有一个头像，点击之后不会跳转 归档 页面

主页头像点击跳转的是`Post`关键字的路径，在主题配置文档中是[这里](https://github.com/Siricee/hexo-theme-Chic/blob/1f9a870c97a15d948febd0bedc35cbe901cf61e9/_config.yml#L9)。所以我猜测你应该是把归档关键字改成别的值了导致的404。这里只有**Post**这个词才能正常链接。

如果你想改成别的词，举例来说如果你想显示Archive，你需要在主题配置文件(themes/Chic/_config.yml)中把Post改为Archive，并在[这行](https://github.com/Siricee/hexo-theme-Chic/blob/1f9a870c97a15d948febd0bedc35cbe901cf61e9/layout/_page/profile.ejs#L4)
```html
<a href="<%- url_for(theme.nav.Posts) %>"><img src="<%- url_for(theme.avatar) %>"></a>
```
改为
```html
<a href="<%- url_for(theme.nav.Archive) %>"><img src="<%- url_for(theme.avatar) %>"></a>
```
即可生效。

但本人不推荐这种方式修改，因为可能其他位置也与这个变量有关联，这样会引起一些潜在的错误。因此请尽量不要擅自修改配置文档中的关键字。

祝您使用愉快:smile:欢迎点个star支持一下
@dabai2017

**Comment by dabai2017** [comment]
已经修复，我查看了layout目录的一些代码，自己改了改。谢谢啦
