### ISSUE TITLE
关于Chic页面刷新后屏幕会短暂的黑一下

### ISSUE THREAD

**Issue by N1ckeyQu** [Siricee/hexo-theme-Chic#101]
Siricee你好，我最近在使用Chic主题，遇到一件挺奇怪的事情，我的博客是https://cookiez.cn/，托管在github上。
自从将博客部署上去后，我发现每次刷新页面屏幕都会黑一下，你可以尝试在我的博客首页快速点击F5，就能明白我的感受了...
我自己本地通过hexo开启服务后，就没什么问题，资源加载的很快，所以我开始怀疑是网络问题导致的，但是我之前使用yilia主题的时候就没碰到过类似的情况，本地是什么样子，部署上去后还是什么样子。
我真的很喜欢这个主题，不明白为什么它会变成这个样子，我有去修改一些js和css（英文改成中文、主题色改为vue绿）,但这应该不是造成问题的原因吧..
麻烦Siricee有空帮我解答下疑惑，感谢！

**Comment by N1ckeyQu** [comment]
我看了一下其他人的博客，好像都存在这个问题。。算了就这样吧

**Comment by Siricee** [comment]
你说的是不是在黑色模式下刷新会闪白一下，亮色模式下我这没这问题啊？
主题默认状态为白色，会先读取本地 localstorge 变量判断是否为黑色模式，所以会有闪白，对于这个问题我暂时还没有很好的办法，所以就没改

**Comment by Siricee** [comment]
目前在这次 [commit](https://github.com/Siricee/hexo-theme-Chic/commit/bfda56eb13a3f7e790e3e2324e74b3ffd8b8a4d8) 之后上述问题已修复

**Comment by N1ckeyQu** [comment]
> 目前在这次 [commit](https://github.com/Siricee/hexo-theme-Chic/commit/bfda56eb13a3f7e790e3e2324e74b3ffd8b8a4d8) 之后上述问题已修复

这个issue我都关了您还在关注，十分感谢，目前pull下来最新代码后，该问题仍然存在，语言有点难以描述，我录了GIF，下图是线上环境连续刷新页面出现的黑屏现象
![GIF 2021-7-17 2-57-26](https://user-images.githubusercontent.com/35259380/125997419-ec6dd8ff-8322-4423-9f95-619b1fcbe0b9.gif)
可以明显看到刷新页面后右上角的切换颜色模式按钮，第一时间是深色模式，然后才切换成亮色模式，我猜想这个是导致黑屏的原因。本地环境并未出现短暂黑屏现象，如下图所示
![GIF 2021-7-17 3-08-22](https://user-images.githubusercontent.com/35259380/125997688-5fa43c9f-6856-4d7c-b3fe-b0f06c18d184.gif)
可以看到刷新页面几乎是无感知的，文字和下方的页码也不会在刷新页面的时候被黑色背景框所包围，这个问题非常怪，本地和线上看到的结果并不一致，我猜测可能是网络延迟将代码中原有的问题放大了
