### ISSUE TITLE
菜单页面排版乱了

### ISSUE THREAD

**Issue by Arost01** [Siricee/hexo-theme-Chic#104]
![d69ae2aa-034d-4775-b609-5d345e282d70](https://user-images.githubusercontent.com/56621038/123914154-ad029b00-d9b1-11eb-9cc4-539540a3e081.png)

**Comment by Siricee** [comment]
看起来没什么问题，你修好了吧

**Comment by Arost01** [comment]
出现乱码了，而且第一页显示了两次，，不过刚才看了下，又正常了，会不会是github的问题
