### ISSUE TITLE
页面元素

### ISSUE THREAD

**Issue by Quetweilan** [Siricee/hexo-theme-Chic#106]
当一个文件夹包含 下列文件
![image](https://user-images.githubusercontent.com/63384895/125387674-db7c6f00-e3d0-11eb-8994-bdd38ecde338.png)

当打开其中一个文件时，能否在页面右侧添加导航，显示该文件夹下其余文件
![image](https://user-images.githubusercontent.com/63384895/125387832-18486600-e3d1-11eb-9e7a-3e71d1977bf5.png)

**Comment by Siricee** [comment]
页面标题下面已经有category分类了，而且还可以直接点进去看到分类下的文章，所以在右侧再单独加一个category分类我觉得不是很有必要。

当然你要是想加可以在自己的博客里加入，写法和 category.ejs 相似，site.categories 变量改为 page.categories即可

**Comment by Quetweilan** [comment]
就是多了一步，不如直接在页面打开方便。

可以请教下怎么写吗，或者在哪里可以学。
对网站的编程纯小白。

**Comment by Siricee** [comment]
去看看前端基础教程，b站视频就可以的，具体到hexo怎么制作的话你有了基本知识可以对照已有的开源主题去写
