### ISSUE TITLE
暗色模式下页面刷新或切换出现闪烁的问题

### ISSUE THREAD

**Issue by BaoXuebin** [Siricee/hexo-theme-Chic#107]
**问题重现**

打开 [https://siricee.github.io/hexo-theme-Chic/](https://siricee.github.io/hexo-theme-Chic/)，将主题切换至 Dark 模式，刷新页面后出现闪烁。

**问题分析**

参考 [layout/layout.ejs/](https://github.com/Siricee/hexo-theme-Chic/blob/master/layout/layout.ejs) 和 [source/js/script.js](https://github.com/Siricee/hexo-theme-Chic/blob/master/source/js/script.js) 两个文件，暗色模式下的主题初始化是在页面加载完成后进行，从而导致页面刚加载完成后主题从 light 切换 dark 造成页面闪烁。

**解决方案**

这里说明一个思路：在页面加载前执行一段 js 代码，去将页面的背景初始化为对应主题的颜色。

```html
<!-- /layout/layout.js -->
<!DOCTYPE html>
<html lang="<%= config.language %>">
<head>
    <%- partial('_partial/head',{cache: true}) %>
</head>
<body>
+  <script>
+      const currentTheme = window.localStorage && window.localStorage.getItem('theme');
+      if ('dark' === currentTheme) {
+          document.getElementsByTagName('body')[0].style.backgroundColor = '#292a2d';
+          document.getElementsByTagName('body')[0].style.color = '#a9a9b3';
+      }
+   </script>
    <div class="wrapper">
        <%- partial('_partial/header',{cache: true}) %>
        <div class="main">
            <%- body %>
        </div>
        <%- partial('_partial/footer',{cache: true}) %>
    </div>
</body>
</html>
```

然后在主题按钮被切换后，将 `body` 设置的样式清除。

```javascript
document.getElementsByClassName('toggleBtn')[0].addEventListener('click', () => {
    if (document.getElementsByTagName('body')[0].classList.contains('dark-theme')) {
        document.getElementsByTagName('body')[0].classList.remove('dark-theme');
+       document.getElementsByTagName('body')[0].style = null;
    } else {
        document.getElementsByTagName('body')[0].classList.add('dark-theme');
    }
    window.localStorage &&
    window.localStorage.setItem('theme', document.body.classList.contains('dark-theme') ? 'dark' : 'light',)
})
```

修改后的效果，可以访问我的网站预览：[https://xdbin.com/](https://xdbin.com/)

The end, Have a nice day :-)

**Comment by Siricee** [comment]
感谢 我去试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月14日(周三) 中午1:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Siricee/hexo-theme-Chic] 暗色模式下页面刷新或切换出现闪烁的问题 (#107)




 
问题重现
 
打开 https://siricee.github.io/hexo-theme-Chic/，将主题切换至 Dark 模式，刷新页面后出现闪烁。
 
问题分析
 
参考 layout/layout.ejs/ 和 source/js/script.js 两个文件，暗色模式下的主题初始化是在页面加载完成后进行，从而导致页面刚加载完成后主题从 light 切换 dark 造成页面闪烁。
 
解决方案
 
这里说明一个思路：在页面加载前执行一段 js 代码，去将页面的背景初始化为对应主题的颜色。
 <!-- /layout/layout.js --&gt; <!DOCTYPE html&gt; <html lang="<%= config.language %&gt;"&gt; <head&gt;     <%- partial('_partial/head',{cache: true}) %&gt; </head&gt; <body&gt; +  <script&gt; +      const currentTheme = window.localStorage &amp;&amp; window.localStorage.getItem('theme'); +      if ('dark' === currentTheme) { +          document.getElementsByTagName('body')[0].style.backgroundColor = '#292a2d'; +          document.getElementsByTagName('body')[0].style.color = '#a9a9b3'; +      } +   </script&gt;     <div class="wrapper"&gt;         <%- partial('_partial/header',{cache: true}) %&gt;         <div class="main"&gt;             <%- body %&gt;         </div&gt;         <%- partial('_partial/footer',{cache: true}) %&gt;     </div&gt; </body&gt; </html&gt;
 
然后在主题按钮被切换后，将 body 设置的样式清除。
 document.getElementsByClassName('toggleBtn')[0].addEventListener('click', () =&gt; {     if (document.getElementsByTagName('body')[0].classList.contains('dark-theme')) {         document.getElementsByTagName('body')[0].classList.remove('dark-theme'); +       document.getElementsByTagName('body')[0].style = null;     } else {         document.getElementsByTagName('body')[0].classList.add('dark-theme');     }     window.localStorage &amp;&amp;     window.localStorage.setItem('theme', document.body.classList.contains('dark-theme') ? 'dark' : 'light',) })
 
修改后的效果，可以访问我的网站预览：https://xdbin.com/
 
The end, Have a nice day :-)

**Comment by Siricee** [comment]
好的 确实可以 感谢您的帮助！！
