### ISSUE TITLE
关于 sidebar

### ISSUE THREAD

**Issue by vaxl029** [Siricee/hexo-theme-Chic#108]
您好，请问是否方便适配sidebar以支持hexo-blog-encrypt插件

**Comment by Siricee** [comment]
sidebar可以随意支持。

hexo-blog-encrypt这个插件我个人觉得完全无用。写博客发布了还要设密码？那为啥不去玩QQ空间呢？这插件的意义在哪呢？

**Comment by vaxl029** [comment]
好的，打扰了，我这就去玩QQ空间
