### ISSUE TITLE
文章里插入图片部署之后无法正常显示

### ISSUE THREAD

**Issue by DestinyIsTo** [Siricee/hexo-theme-Chic#109]
文章里插入图片部署之后无法正常显示，我把图片也放到了文章同源文件夹下，路径是相对路径，但是就是无法正常显示

**Comment by DestinyIsTo** [comment]
![2c376ae955636daa3a77afeea3a831a](https://user-images.githubusercontent.com/89471683/130801342-8a31bc6a-e5b0-4436-acf6-756ec3479679.png)

**Comment by Siricee** [comment]
看起来已经好了诶 那我关掉这个issue了
