### ISSUE TITLE
Some questions about homepage messages

### ISSUE THREAD

**Issue by MoYoez** [Siricee/hexo-theme-Chic#11]
I want to add message function on the basis of this topic through the third party platform (**LiveRe**). I have been fumbling for a long time and I don't know how to change it. Please consult the setup plan. Thank you.

**Comment by Siricee** [comment]
If you are referring to **comment system**, I am sorry to say that I regard comment function as a **unnecessary function** of  private blog, so I will NOT integrated it as a origin function in my theme in recent future, temporarily at least.

However you can setup it by yourself if you need it. Here are some articles below for your reference.
- [为Hexo博客添加LiveRe评论系统 - 掘金](https://juejin.im/post/5a632dfcf265da3e484be90c)
- [为 Hexo 博客主题 NexT 添加 LiveRe 评论支持 | 字节流的博客](https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html)
- [liveRE instructions](https://livere.com/insight/myCode)
@MoYoez

**Comment by MoYoez** [comment]
Thanks a lot.I will try it in my own page.At last,The hexo theme is nice,hope you can do better at this theme.Thanks
