### ISSUE TITLE
作者你好，关于文字修改成icon

### ISSUE THREAD

**Issue by exlucas1** [Siricee/hexo-theme-Chic#112]
我在post.ejs中修改后无法显示，请问要怎样才能实现呢？
![AFF99DED-51C8-44F1-9437-A52FAEB486A3](https://user-images.githubusercontent.com/49865475/141271402-15adc744-9536-4efa-bdc7-26f4cc900aa7.png)

**Comment by exlucas1** [comment]
还有一个问题，就是现在的toc已经无法显示了

**Comment by Siricee** [comment]
不好意思 好久都没看这边issue了…今天晚上就修一下

**Comment by Siricee** [comment]
> 我在post.ejs中修改后无法显示，请问要怎样才能实现呢？ ![AFF99DED-51C8-44F1-9437-A52FAEB486A3](https://user-images.githubusercontent.com/49865475/141271402-15adc744-9536-4efa-bdc7-26f4cc900aa7.png)

你要同时更新iconfont中的图标文件才可以正确显示，只改类名缺失图标文件本身。
具体操作请参考这里https://github.com/Siricee/hexo-theme-Chic/issues/69
