### ISSUE TITLE
為甚麼iconfont無法顯示?

### ISSUE THREAD

**Issue by bear1222** [Siricee/hexo-theme-Chic#115]
您好，我希望在首頁的連結新增codeforces的icon，已經按照之前大大提到的方法下載並放到fonts資料夾中，從網頁上的html中看起來應該是有讀到這些檔案的，但卻始終無法顯示這個icon，希望大大能幫忙看看，謝謝！

![image](https://user-images.githubusercontent.com/86869648/154090613-9c531230-c898-4b81-864e-669b11f5d72a.png)
![image](https://user-images.githubusercontent.com/86869648/154091117-adad8b54-8b3e-4143-88cc-a3f6b6b5a116.png)

**Comment by Siricee** [comment]
你把fonts里面的`iconfont2`文件夹重命名为`iconfont`，把原来的`iconfont`删掉试试。估计你是添加font之后忘了改名了吧

**Comment by bear1222** [comment]
把原來的iconfont刪掉的話，codeforces的圖標還是沒有出來，而且其他的icon也會一起不見。
剛才發現我下載的資料夾中好像有少一些檔案(.svg跟.eot)，不知道是不是這個問題，如果是這個問題的話應該如何解決呢?

**Comment by Rqcker** [comment]
@bear1222 请问是怎么解决的呢？我模仿你的github还有这个issue的指导加上了 `url('iconfont.woff?t=xxxx') format('woff'),`但还没有解决该问题。

**Comment by Rqcker** [comment]
> [@bear1222](https://github.com/bear1222) 请问是怎么解决的呢？我模仿你的github还有这个issue的指导加上了 `url('iconfont.woff?t=xxxx') format('woff'),`但还没有解决该问题。

搞定了，可以提醒看到这个issues的朋友，注意从iconfont下载时候icon class不要有大写，要全部小写是最方便的。然后config里随意大小写
