### ISSUE TITLE
大佬，你这个About页面咋添加啊

### ISSUE THREAD

**Issue by Myoontyee** [Siricee/hexo-theme-Chic#117]
大佬，你这个About页面咋添加啊
我那个关于页面老是说404，找不到文件夹

用`hexo new page about`也不对啊，还是说找不到

**Comment by Siricee** [comment]
能贴个图吗，我看描述不知道问题在哪…这个页面比category还好搞，样式都不用配置

**Comment by Myoontyee** [comment]
佬，我刚刚搞定了，不好意思
我用`hexo new page about`
然后About大写改小写就行了
![图片](https://user-images.githubusercontent.com/40823733/156998520-78dcb91d-4733-407b-9f47-3368f72b4342.png)
![图片](https://user-images.githubusercontent.com/40823733/156998596-e3211099-533f-4dd0-aa5c-35283298b3bf.png)

给佬添麻烦了，谢谢！

**Comment by Myoontyee** [comment]
我之前因为是home new page About
nav:
   关于:about

所以没法显示，我没想到还有大小写的问题..

**Comment by Siricee** [comment]
哈哈哈祝使用愉快！分享而已无所谓什么大佬
