### ISSUE TITLE
代码块样式问题

### ISSUE THREAD

**Issue by Robotunl** [Siricee/hexo-theme-Chic#118]
如图：
<img width="518" alt="image" src="https://user-images.githubusercontent.com/81059303/157047152-5ca78b01-2245-4b57-bcf5-06a918f532ed.png">

**Comment by Robotunl** [comment]
大概是解决了 修改 themes/chic/source/css/variable.styl 中的`$dark-code-font-color`和
`$dark-code-background-colo`就行了。
不过不知道白色背景怎么设置（想改成深色

**Comment by Siricee** [comment]
不用这么麻烦。。你直接去[这里](https://github.com/Siricee/hexo-theme-Chic/blob/31086e5d49f39fef4d6de97ea538c3b7de04e246/source/css/style.styl#L38)换个代码块的主题就行了，我预先放进去很多种风格，亮色暗色都有的
