### ISSUE TITLE
[BUG]文章缩进等错误

### ISSUE THREAD

**Issue by Lemonawa** [Siricee/hexo-theme-Chic#120]
对比图：
VScode：
![image](https://user-images.githubusercontent.com/69106050/158222779-fc250918-3b8c-4b64-aa31-706f296782b9.png)
实际博客：
![image](https://user-images.githubusercontent.com/69106050/158222840-838ce80c-b040-4a7e-8481-8aaf224ad6ca.png)
@Siricee

**Comment by Siricee** [comment]
“3. SSH操作工具”和“###操作步骤”空一行试试。

尽量用hexo s代替vscode预览，因为vscode的规则和hexo的markdown解析器不是同一个
