### ISSUE TITLE
[BUG与咨询]文章到第二面以后，icon图标不再显示

### ISSUE THREAD

**Issue by Myoontyee** [Siricee/hexo-theme-Chic#121]
在第一面是正常的，在第二面开始就不正常了，如果从类别、标签进入，也是不正常的，推测是缺少引用iconfont库？可是第一面又正常，另我不知道在哪个文件加这个引用才能生效
![图片](https://user-images.githubusercontent.com/40823733/158504773-63ce193e-3aad-41dd-80fd-cb115e486f4a.png)
![图片](https://user-images.githubusercontent.com/40823733/158504810-b9ab066f-bb83-4afe-93a0-f9cae539fa48.png)
![图片](https://user-images.githubusercontent.com/40823733/158504887-ca77c3cf-0f7d-4c4b-b1a4-204a94130fa6.png)
![图片](https://user-images.githubusercontent.com/40823733/158504913-d11a18d8-2043-4381-bb22-75f20efd9d76.png)

**Comment by Myoontyee** [comment]
已解决，在`themes\Chic\_config.yml`直接添加全局引用样式即可
![图片](https://user-images.githubusercontent.com/40823733/158505270-9fc1b58b-82cc-4bca-aa6e-d2f55c3acf7b.png)

**Comment by Siricee** [comment]
Okay. Well done.
