### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by tianqi-bucuo** [Siricee/hexo-theme-Chic#127]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/39249387/175065975-17d44654-78b5-4746-b084-afd74fa3fa70.png">

点击某个分类，进去之后显示上图，看了一下在publish/category文件夹下也没有生成对应的html文件；

有人遇到过这种情况吗

**Comment by Siricee** [comment]
看下[文档](https://github.com/Siricee/hexo-theme-Chic/blob/master/README-CN.md#添加tagcategory页面)和[FAQ第一个问题](https://github.com/Siricee/hexo-theme-Chic/blob/master/README-CN.md#faq-提问)

**Comment by Siricee** [comment]
不知道是不是这个问题 https://github.com/Siricee/hexo-theme-Chic/issues/126 你可以执行下 `npm install` 试试看是否能解决
