### ISSUE TITLE
moment.js 時間格式

### ISSUE THREAD

**Issue by nataliepjlin** [Siricee/hexo-theme-Chic#128]
如題，已參考 https://momentjs.com/docs/#/displaying/format/。
如果只想顯示 `MMMM D, YYYY` 而去掉 `config_yml` 裡的  `time_format` 無法實現。 想請問如何修改!

**Comment by Siricee** [comment]
没看懂，为什么想显示`MMMM D, YYYY`却要去掉`time_format`？format就是帮你格式化的啊

**Comment by nataliepjlin** [comment]
> 没看懂，为什么想显示`MMMM D, YYYY`却要去掉`time_format`？format就是帮你格式化的啊

只想顯示日期但不要時間

**Comment by Siricee** [comment]
> > 没看懂，为什么想显示`MMMM D, YYYY`却要去掉`time_format`？format就是帮你格式化的啊
> 
> 只想顯示日期但不要時間

哦哦哦 如果你不想改源码，你可以把 [主题里的config文件](https://github.com/Siricee/hexo-theme-Chic/blob/c4f766e636c09610d5d36bcb89038fc04987702f/_config.yml#L85) time_format改成这样：
```diff
- time_format: H:mm:ss
+ time_format: ' '  # 引号 空格
```
但这方法会多一个空格。

或者你可以直接到 [源码](https://github.com/Siricee/hexo-theme-Chic/blob/c4f766e636c09610d5d36bcb89038fc04987702f/layout/_page/post.ejs#L19) 里删掉
```diff
-  Date: <a href="#"><%- date(page.date, theme.date_format)  %>&nbsp;&nbsp;<%- time(page.date, theme.time_format)%></a>
+  Date: <a href="#"><%- date(page.date, theme.date_format)  %></a>
```
就可以了
