### ISSUE TITLE
toc栏折叠后点击小标题闪烁

### ISSUE THREAD

**Issue by JesseJeson** [Siricee/hexo-theme-Chic#131]
[record.webm](https://user-images.githubusercontent.com/55904993/178898737-4ae0d51b-58a0-47f4-8b21-8746ec9d89b4.webm)
不知道是不是因为只有一个大标题，这是bug吗QWQ

**Comment by Siricee** [comment]
这个应该是插件tocbot的bug…我之前没有遇到同样的问题我就没修…
