### ISSUE TITLE
咨询标签和分类的问题

### ISSUE THREAD

**Issue by Camellia-2** [Siricee/hexo-theme-Chic#139]
首先非常感谢您提供的主题,我很是喜欢您的风格,我是初次使用hexo我把我的问题描述如下,希望能够得到解答;

1. 我按照您的说明流程操作完了所有步骤只是不知道知否完全正确.
2. 我在执行完 hexo new page tag  hexo new page category这两项命令后,分别到路径/hexo/blog/source/tag和/hexo/blog/source/category下修改了index.md文件,修改格式我会在下方图片展示.
3. 这些操作完后,主页的标签和分类都已经可以正常显示,只是我在测试文章后发现文章并没有真正的被归纳.
4. 是否还需要配置 _config.yml文件?如果需要我应该怎么配置?是配置blog目录下的还是Chic目录下的.

最后还是要感谢您的无私风险,非常感谢!
![Uploading 1.jpg…]()

**Comment by Camellia-2** [comment]
上边的贴图好像没能成功![1](https://github.com/Siricee/hexo-theme-Chic/assets/149544854/d0375cde-6457-4c9f-b274-5b6eaeebb25b)

**Comment by hunkjun** [comment]
我也遇到了同样的问题!

**Comment by Camellia-2** [comment]
> 我也遇到了同样的问题!

解决了吗?我感觉我的流程应该没错,可能与Hexo的环境有关,我是在Docker下安装的环境,您呢?

**Comment by Siricee** [comment]
https://github.com/Siricee/hexo-theme-Chic/issues/139#issuecomment-1788300293 这图上注意frontmatter格式，layout后面一定要有个空格 
```md
- layout:category
+ layout: category
```
另外我没有测过docker的可用性，不知道你用这种插件的形式添加标签是否正确，可以把文章添加过tag/category后的frontmatter发个截图吗？

**Comment by Camellia-2** [comment]
> [#139 (comment)](https://github.com/Siricee/hexo-theme-Chic/issues/139#issuecomment-1788300293) 这图上注意frontmatter格式，layout后面一定要有个空格
> 
> ```
> - layout:category
> + layout: category
> ```
> 
> 另外我没有测过docker的可用性，不知道你用这种插件的形式添加标签是否正确，可以把文章添加过tag/category后的frontmatter发个截图吗？

是的,谢谢您的解答,这个问题已经解决掉了,icon还是没能解决,我把框架暂时搬离了服务器,过几天我到新服务器截图给你看下,我在重新测试下icon,还不行的话我发给你icon的包你看看
