### ISSUE TITLE
关于iconfont图标没有更换成功的提问

### ISSUE THREAD

**Issue by Camellia-2** [Siricee/hexo-theme-Chic#140]
## 我的操作步骤
---
1. 我首先把代码包解压缩后放在了此路径 **/Chic/source/fonts** 并重命名为 **zidingyi**
2. 到路径 **/Chic/source/css**  下编辑了 **style.styl** 并曾加了 `@import "../fonts/zidingyi/iconfont.css"`
3. 到路径  **/Chic/layout/_page** 下编辑了 **profile.ejs** 并曾加了 `<link rel="stylesheet" href="../fonts/zidingyi/iconfont.css">`
4. 到路径 **/Chic** 下编辑了 **_config.yml**  在这里的 **links:** 项下曾加了对应的图标名,进入博客没有改变.
5. 清理浏览器缓存,尝试 hexo clean 重新入博客 依然没有改变
6. 以为编辑 **_config.yml** 添加图标名时会有顺序问题,重新按照代码里的图标名排序依然不行
7. 编辑 **_config.yml** 时确实会有缩进错误,会导致主页打不开,修正缩进后能正常进入但是图标始终不能显示 
8. 我怀疑是不是我在 www.iconfont.cn 下载的代码步骤不对?我会贴图上来,麻烦您帮我看下问题在哪
---

**Comment by No-9527149** [comment]
同问，我也想加上一个邮件的icon，期待解答

**Comment by Siricee** [comment]
@Camellia-2 @No-9527149 请问看过 https://github.com/Siricee/hexo-theme-Chic/issues/38#issuecomment-1067958574 这个文章吗？如果看过这篇文章后并没有解决问题，请把你下载的那个iconfont压缩包邮件发给我我测试一下看看什么问题，仅图上描述的我感觉好像没什么操作上的错误……

**Comment by No-9527149** [comment]
> @Camellia-2 @No-9527149 请问看过 [#38 (comment)](https://github.com/Siricee/hexo-theme-Chic/issues/38#issuecomment-1067958574) 这个文章吗？如果看过这篇文章后并没有解决问题，请把你下载的那个iconfont压缩包邮件发给我我测试一下看看什么问题，仅图上描述的我感觉好像没什么操作上的错误……

我这里已经解决了，非常感谢^^

**Comment by Rqcker** [comment]
@Siricee @No-9527149 @Camellia-2  请问大家是如何解决的呢？那个文章已经不能再访问了，我现在也遇到icon不显示的问题。

**Comment by Rqcker** [comment]
> [@Siricee](https://github.com/Siricee) [@No-9527149](https://github.com/No-9527149) [@Camellia-2](https://github.com/Camellia-2) 请问大家是如何解决的呢？那个文章已经不能再访问了，我现在也遇到icon不显示的问题。

搞定了，可以提醒看到这个issues的朋友，注意从iconfont下载时候icon class不要有大写，要全部小写是最方便的。然后config里随意大小写。

**Comment by yingyu5658** [comment]
> > [@Siricee](https://github.com/Siricee) [@No-9527149](https://github.com/No-9527149) [@Camellia-2](https://github.com/Camellia-2) 请问大家是如何解决的呢？那个文章已经不能再访问了，我现在也遇到icon不显示的问题。
> 
> 搞定了，可以提醒看到这个issues的朋友，注意从iconfont下载时候icon class不要有大写，要全部小写是最方便的。然后config里随意大小写。

老哥可以把你的配置文件发我一份看看吗，我这试了好久都没解决
