### ISSUE TITLE
Categories重复显示如何解决？

### ISSUE THREAD

**Issue by Alpaca10086zyys** [Siricee/hexo-theme-Chic#143]
蒟蒻求问……在修改过一次分类标准之后出现了有重复的文件夹但是是空的，楼主还是学生，虽然是记录为主的博客但这样有点丑想问问有没有什么办法？

**Comment by Alpaca10086zyys** [comment]
在别的主题下面找到了一个解决方法是先hexo clean再generate，尝试了一下似乎可以（但是要等一会），有没有佬可以解释一下原理？感觉对网页的架构还有很多不理解的地方，求带~

**Comment by Siricee** [comment]
其实就是 hexo 生成静态文件时会留下部分缓存数据，你的文章 md 删除了但数据没删掉就会这样。hexo clean 就是用来删除生成的缓存数据的
