### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by USTC-Keyanjie** [Siricee/hexo-theme-Chic#15]
Please tell me how to change the font in this theme.

请告知如何修改主题中的字体。

**Comment by Siricee** [comment]
[theme/Chic/source/css/font.styl](https://github.com/Siricee/hexo-theme-Chic/blob/1f9a870c97a15d948febd0bedc35cbe901cf61e9/source/css/font.styl#L10)中
```css
$font-family = 'Microsoft Jhenghei',Lantinghei SC, 'lanting', PingFang SC, Seguo UI, Microsoft Yahei, Arial
```

**Comment by AlisonWen** [comment]
請問如何單獨改首頁標題的字體呢?

**Comment by Siricee** [comment]
您好，您的邮件已收到，我稍后会回复。
