### ISSUE TITLE
Space after apostrophe ( ' )

### ISSUE THREAD

**Issue by antoniusostermann** [Siricee/hexo-theme-Chic#16]
With the fonts shipped with this layout, there is an awkward space after each apostrophe:

![image](https://user-images.githubusercontent.com/2332002/64078670-d121c200-ccdd-11e9-9335-383c84358d1d.png)

In the source code, it's a regular apostrophe: 
  `Awesome Hexo-theme built by Siricee. Since I’m not great at designing, adopted this. :-)`
Although it's not ( ' ), but converted to ( ’ ).

If I change the CSS to disable all fonts except Arial, everything works. So this seems to be an issue with the fonts used.

See also:
* https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_windows8-mso_365hp/the-extra-space-after-an-apostrophe-problem-solved/33c0e569-f3cf-4646-9572-b700241164b2
* https://github.com/iTimeTraveler/hexo-theme-hipaper/issues/26

**Comment by Siricee** [comment]
It seems indeed. 
I used 'Microsoft Jhenghei' as the first font, But this font seems to convert apostrophe in English to an apostrophe and a space appended.

The fonts in this theme are suitable for Chinese, although it will cause this problem, So you can delete Chinese favored fonts in `hexo-theme-Chic/source/css/font.styl`
```css
$font-family = 'Microsoft Jhenghei',Lantinghei SC, 'lanting', PingFang SC, Seguo UI, Microsoft Yahei, Arial
// 'Microsoft Jhenghei',Lantinghei SC, 'lanting', PingFang SC are Chinese favored fonts.
```
or change them to English favored fonts.

Thank you for your advise.

**Comment by inkss** [comment]
and 有一个感觉，文章字体似乎太纤细了，阅读起来有些吃力呀

**Comment by Siricee** [comment]
> and 有一个感觉，文章字体似乎太纤细了，阅读起来有些吃力呀

那你可以参考这个 https://github.com/Siricee/hexo-theme-Chic/issues/15 自己改个字体吧，其实把第一个去掉就行了，从方正兰亭开始的字体就没这么细了

**Comment by MarceloBarrera** [comment]
When I changed it to use "Microsoft Yahei UI" instead of "Microsoft Yahei" then it worked fine for me.

**Comment by Siricee** [comment]
> When I changed it to use "Microsoft Yahei UI" instead of "Microsoft Yahei" then it worked fine for me.

ohh~thanks! I'll try it:smile:
