### ISSUE TITLE
代码段和引用段没有自动换行

### ISSUE THREAD

**Issue by tplish** [Siricee/hexo-theme-Chic#18]
小白一个(●'◡'●)

**Comment by Siricee** [comment]
你好，请详细描述你的问题

**Comment by tplish** [comment]
当引用文字过长，或代码段某一行太长，不知道怎么自动换行。然后就会超出浏览器宽度。
![issue](https://user-images.githubusercontent.com/43607119/64396786-641d7c00-d091-11e9-9c4c-da38961ca635.png)

**Comment by Siricee** [comment]
引用文字的markdown语法为
&gt; balabala
代码段语法为

`

`

`

balabala（三个反引号）

`

`

`


你用的是代码块语法，当然不会换行。


 
---原始邮件---
发件人: "tplish"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 上午10:32
收件人: "Siricee/hexo-theme-Chic"<hexo-theme-Chic@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Liu Zijian"<1165728679@qq.com&gt;;
主题: Re: [Siricee/hexo-theme-Chic] 代码段和引用段没有自动换行 (#18)



当引用文字过长，或代码段某一行太长，不知道怎么自动换行。然后就会超出浏览器宽度。

**Comment by tplish** [comment]
对不起，那个引用是我的学艺不精。因为以前某个编辑器里面是可以tab键引用的，我道歉。

但是那个代码段，我记得有两种方案。
1. 一种是显示时类似自动换行但是没有行号
2. 另一种就是类似github上有一个横向滚动条，以保证不会超越浏览范围。

```
long code long code long code long code long code long code long code long code long code long code long code long code long code long code long code long code long code long code long code long code 
```

我就提提意见，顺便研究学习，你也别生气。:smile:

**Comment by Siricee** [comment]
本主题没有第一种方案，就是自动换行没有行号的那种。代码段并不是用highlightjs渲染，所以不受控制，强制高亮、自动换行、显示行号。

另外本主题的代码段是支持横向滚动条的，当代码宽度大于代码块限制宽度就会产生滚动条。效果请见文档中标注的示例站。
另外hexo支持特殊markdown语法，请见 [标签插件（Tag Plugins） | Hexo](https://hexo.io/zh-cn/docs/tag-plugins)
