### ISSUE TITLE
文章太长时，文章显示不全

### ISSUE THREAD

**Issue by tplish** [Siricee/hexo-theme-Chic#19]
正常情况：
![q1](https://user-images.githubusercontent.com/43607119/64539397-fe5f1780-d350-11e9-8b7f-665a42ac9694.png)

稍微增加内容后：
![q2](https://user-images.githubusercontent.com/43607119/64539234-b63ff500-d350-11e9-993b-957d62a1e594.png)

之后的内容都无法显示，footer也没有显示。

**Comment by Siricee** [comment]
从没遇到过这种情况，个人感觉像是hexo的问题而不是主题的。请详细反馈下这个问题环境我排查一下吧。
多少字数会触发这个问题？控制台中有没有报错，浏览器console中有没有报错？hexo g能不能正常执行？你这文章里有没有hexo不能正常解析的符号/标签等

**Comment by tplish** [comment]
控制台没有报错、浏览器console没有报错，hexo g正常执行。

我重新克隆项目，不加修改，然后写了个测试文件，可以重现问题。
```C++
#include <bits/stdc++.h>
using namespace std;

const string header = "\
---\n\
title: test\n\
---\n\
";

const string content = "\
#### 模板方法\n\
>定义一个操作中的算法骨架，而将算法的一些步骤延迟到子类中，使得子类可以不改变该算法结构的情况下重定义该算法的某些特定步骤。它是一种类行为型模式。\n\
#### 策略模式\n\
>该模式定义了一系列算法，并将每个算法封装起来，使它们可以相互替换，且算法的变化不会影响使用算法的客户。策略模式属于对象行为模式，它通过对算法进行封装，把使用算法的责任和算法的实现分割开来，并委派给不同的对象对这些算法进行管理。\n\
#### 组合模式\n\
>有时又叫作部分-整体模式，它是一种将对象组合成树状的层次结构的模式，用来表示“部分-整体”的关系，使用户对单个对象和组合对象具有一致的访问性。\n\
";

const int n = 100;

int main(){
    freopen("a.out","w",stdout);

    cout << header << endl;

    for (int i=1; i<=n; i++){
        cout << "## " << i << endl;
        cout << content << endl;
    }
    return 0;
}
```

![q3](https://user-images.githubusercontent.com/43607119/64575973-f4690300-d3a8-11e9-9a44-6525e5bde079.png)

编译运行`a.cpp`，把测试文件生成的`a.out`文档改为`test.md`用于文章发布，在序号54处就出现改问题了。没试过软件测试不知道怎么描述问题，不知道这样你是否清楚。

**Comment by Siricee** [comment]
。。。
![捕获](https://user-images.githubusercontent.com/25154957/64619764-34fe6600-d415-11e9-92cc-23723d48f112.PNG)

**Comment by Siricee** [comment]
![jike_172912931609189_pic](https://user-images.githubusercontent.com/25154957/64620571-b276a600-d416-11e9-9f94-7bb86af770e5.jpeg)

**Comment by tplish** [comment]
虽然你这个样子好像瞧不起我，但我已经尝试了好几次，清空文件，重新生成静态，删除浏览器缓冲什么的，还是这个样子。文章太长，后面就是会显示不出来。

然后就是，问题是在hexo s的时候出现的，hexo d的时候反而没有。

虽然你这稍显嘲讽，不过也无所谓了，比较我小白，遇到问题大概率四处碰壁。

😢

**Comment by Siricee** [comment]
![jike_172912931609189_pic](https://user-images.githubusercontent.com/25154957/64620851-36c92900-d417-11e9-830b-91dadb39b460.jpeg)

**Comment by tplish** [comment]
那最后，先感谢你为开源做出的贡献吧。

不过这遇到别人提BUG的态度，祝你以后路子再走宽点吧。

**Comment by Siricee** [comment]
有问题请描述问题，而不是在issue里先注明自己是小白。你是不是小白我完全不关心，也对解决问题没有任何帮助。

关于issue的格式你可以看下 [如何正确的提出一个 Issue?](https://zhuanlan.zhihu.com/p/52370003) 这篇文章，在开源社区中尽量以问题现象+报错信息+环境+截图的形式提出，减少沟通成本。

PS：我这人和黄药师态度很像，你觉得我很平和我就很平和，你觉得我嘲讽那我就是在嘲讽。

祝主题使用愉快，有问题可以添加issue或email提问。针对本作品我会就事论事，维护到底。

PS2：是不是bug请先在自己环境大致确定再说，尽量不要抛出一个不确定的问题。

**Comment by tplish** [comment]
1. 先注明小白正是因为什么都不懂，希望帮助。你提的这个“如何正确的提出一个Issue”就很nice。我也非常感谢你。

2. 玻璃心不玻璃心不是这么看的，我肯这么问，也肯定有被别人说菜的心理准备。真正的问题在于，这是我的疏忽而不是主题的问题，你大可直接指出来，而不是发两个表情包，然后又删掉来说教。

再次，感谢你关于Issue的意见。初入Github我真心感谢这些意见。然后，如果主题有什么问题，我还是会过来问的。

**Comment by Siricee** [comment]
没有菜不菜这一说，所有人在github上都是学习者，闻道有先后而已。

<del>表情包这个发言吧，我添加后又觉得不妥就删掉了，忘了还有邮件抄送这事了</del>，确实是我的不对，在这里道个歉。。对不起 我太草率了。

最后感谢你的使用和对本主题的支持。这些信息虽然不是实际出错但也起码算是为hexo做出了测试用例的贡献了，如果有其他问题我会继续解决。
