### ISSUE TITLE
如何解决文章标题较长时categories页面标题显示不全的问题？

### ISSUE THREAD

**Issue by JinhangZhu** [Siricee/hexo-theme-Chic#20]
作者你好，我使用你的主题已经一周了，非常喜欢此主题的极简风。但在使用过程中，碰到了如下的问题。
#### 使用背景
- 手机端或者桌面版浏览器宽度缩放到比较窄时
- 文章标题较长
#### 问题
- 电脑上没有滚动条用来看全标题
- 手机上无法触摸看全标题
#### 图片
![电脑端](http://i2.tiimg.com/698611/17a904dbe759a1fd.png)
### 希望达到的效果
- 电脑端上当标题长度超出宽度的时候，每一个category下能否可以加一个滚动条，往右滚动时，一个category的所有标题一起移动？
- 手机端同理，能否实现通过触摸移动就可以看全标题？

非常感谢作者的辛苦努力，如果作者有其他的细节问题，我会尽快给出😀。

**Comment by Siricee** [comment]
首先感谢您对本主题的支持哈:smile:

你提到的这个问题，我之前也思考过，有没有什么不破坏大局的改动方式，能在不破坏原有版面设计同时达到文章标题的全显示呢？最后想了半天也没想出个完美的方案来，所以这个项目就一直维持这个样子。。

你下面说的这个**希望达到的效果**，这个完全可以实现。

首先说下怎么实现：

1. 桌面端的样式添加滚动条：
在文件`themes\Chic\source\css\_page\category.styl` 代码具体位置在[这里](https://github.com/Siricee/hexo-theme-Chic/blob/9928b1d1226f981ea47eae32c7d0fe2c9f5bc94d/source/css/_page/category.styl#L24)
```styl
.post-wrap
  .categories-card
    margin 0 auto
    margin-top 1em
    display flex
    align-items center
    justify-content space-between
    flex-direction row
    flex-wrap wrap
    padding 0 2.5em
    line-height 1.6em
    .card-item
      font-size 14px
      text-align left
      width 45%
      display flex
      align-items flex-start
      margin-top 2em
      min-height 16em
      padding 0 2%
      position relative
      overflow auto  // 这里添加这句
      //.categories
        // overflow hidden  // 将这行注释掉或删掉
```
2. 移动端的样式添加滚动条：
在文件`themes\Chic\source\css\media.styl`中，代码具体位置在[这里](https://github.com/Siricee/hexo-theme-Chic/blob/9928b1d1226f981ea47eae32c7d0fe2c9f5bc94d/source/css/media.styl#L154)
```styl
// ... 省略部分代码
  .categories
    .categories-card
      .card-item
        width 100%
        display: flex
        min-height 0
        overflow auto // 这里添加这句
        //.categories
          // overflow: hidden  // 将这行注释掉或删掉
```

经过以上两处修改即可完成你说的效果，在文字超出长度时会自动触发滚动条。

**测试效果：**
在桌面版Chrome 69中表现为超出宽度会显示有样式的滚动条；
在桌面版Chrome 69的移动端devTools模拟环境下表现为移动端超出宽度会显示有样式的滚动条。
（替换了Chrome默认的滚动条样式，默认非常粗严重破坏整体视觉效果）
注：在其他浏览器下可能表现有差异。

**但这个修改方式我认为还是有待改进**。

（以下是我的个人观点）从视觉设计上来说，如果加入滚动条：
- 在所有category和标题都超出长度的情况下，全部触发滚动，会造成页面整体非常不稳定的感觉（到处都在滑），而这个页面的视觉焦点集中在中央分类块上，这个不稳定感可能会明显造成不适（其实没这么严重，就是感觉别扭）。
- 在多组分类块只有一个超出长度触发了滚动条的情况下，这个带滚动条的块又会造成版式不对称、破坏页面风格的一致性。

**我个人对页面整体布局和版式非常在意，这个改动我觉得还不够理想，因此暂时不会添加至发布版本中**。等我再看些类似这种情况的网站有比较好的处理时我会修正这个问题。（有什么推荐的设计也可以提出来我参考下）所以目前的办法其实是建议标题尽量短些，以15个中文字符以内最佳。

但我给你修改的这个代码整体来说暂时还是可以的，因为不移动超长文字块时滚动条不会显示；而显示时也有特定样式避免默认样式。

以上就是我对您的这个问题作出的回复，你可以测试一下看看效果如何，有什么建议或者反馈欢迎一起交流。

最后再次感谢您对本作品的支持和肯定。祝您使用愉快！！:sunglasses:

**Comment by JinhangZhu** [comment]
首先我表示非常感谢作者的及时回复！

但是由于我最近几天忙于在学校安定可能没啥时间哈哈，您的方案我一定在`9月20日`前测试并且给出反馈。
### 对于作者的测试效果的感觉
对于作者已经完成的测试，我觉得描述得非常详细了。对于页面布局和版式的问题，我也比较在乎，**希望网站能够在足够简单的操作中展示关键有效的信息**。可能之后完成测试之后才能做出是否要完成这个需求的决定。

我的反馈目前就是这样，因为还没做测试所以没办法给出更多的信息。

最后，感谢作者百忙之中还这么认真地回答了我的issue！向你学习，共同进步！💪
