### ISSUE TITLE
添加评论功能

### ISSUE THREAD

**Issue by maojinyuan** [Siricee/hexo-theme-Chic#22]
大神能不能写个添加评论的脚本，有的时候互动评论也蛮重要的呢？

**Comment by Siricee** [comment]
目前本主题暂时不支持评论系统。我觉得个人博客不需要评论模块，加上评论的个人博客和掘金、CSDN、简书没什么区别了。

关于如何添加评论请看这里 https://github.com/Siricee/hexo-theme-Chic/issues/8
