### ISSUE TITLE
关于三个问题的请教

### ISSUE THREAD

**Issue by maojinyuan** [Siricee/hexo-theme-Chic#23]
Hello,你好，关注你了你的主题，觉得非常棒，但是仍有3个问题想请教一下：
1.利用markdown语言编辑一级标题的时候，这个标题为什么会有个#号？  我可以在哪串代码里面去除，作为标题，感觉有个#号怪怪的。
2. 我的无序标签可以和正文格式一样顶格吗？这里明显看到没有顶格，当然这个问题不知道是你主题的代码设置是这样，还是markdown里面可以设置？如果是后者，知道的话还希望不吝赐教.
3.关于注释块问题，我觉得是不是过于太高了，理论上编辑的注释块的文本应该是我标注了的红线高度，请问这个我可以在哪里调节呢？
最后，非常感谢你有时间回答我的问题，这个主题确实太棒了~!~感动到哭。
![problem](https://user-images.githubusercontent.com/20769696/65589092-170b3680-dfbb-11e9-9eeb-0b1a26741d76.png)

**Comment by Siricee** [comment]
首先感谢您对本主题的支持哈！

下面是对以上问题的回复：
1. 这个问题请看 https://github.com/Siricee/hexo-theme-Chic/issues/5

2. 无序标签可以顶格。

请修改[这里](https://github.com/Siricee/hexo-theme-Chic/blob/eaefcc3aed97f9d4780524bea61590830d73a512/source/css/_page/_post/post_content.styl#L88)代码：
```css
  ul
    padding-left 2em
```
改为
```css
  ul
    margin-left: -2em
```
3. 你说的注释块是不是用'>'开始的**引用块**? 如果是的话请修改[这里](https://github.com/Siricee/hexo-theme-Chic/blob/eaefcc3aed97f9d4780524bea61590830d73a512/source/css/_page/_post/post_content.styl#L129)
```css
blockquote
    // ...省略部分代码
    padding 1em 1.2em 1em 1.2em
```
改为
```css
blockquote
    // ...省略部分代码
    padding 0em 1.2em 0em 1.2em
```
你说的这个太高了是因为你这个截图是单行引用文本，在**多行引用文本**中缩短上下边距会造成横向过宽的感觉，我个人不建议修改。

祝您使用愉快，喜欢本作品的话欢迎点右上角star支持一下，谢谢！

**Comment by maojinyuan** [comment]
你好，还有一个问题，就是有序列表，我看你没用写啊。我自己在.post-content里面添加了ol，设置了margin-left -2em。在本地测试的时候是可以的，但是deploy到github上面再打开距离最左侧还是有间距，这应该怎么解决呢？
