### ISSUE TITLE
怎么删除多余且已经无用的标签或者分类?

### ISSUE THREAD

**Issue by EgoSay** [Siricee/hexo-theme-Chic#25]
开始尝试搭自己的博客, 找到了您这个主题很喜欢, 感谢设计出这个主题~
现想咨询一个问题: 如下图, 这些标签是测试生成的, 现在我想删除这些标签
![image](https://user-images.githubusercontent.com/23449203/65831139-e5f77280-e2e8-11e9-8026-2a225f734e5a.png)

我尝试过修改 生成的tag/index.html文件删除多余的标签, 可是无效, 其他的资源文件我也看了一下, 不知道修改哪里才能生效.

**Comment by Siricee** [comment]
这个好像是Hexo的问题，你执行下`hexo clean`再重新`hexo g`这个就没有了。

原因是public目录是生成的，手动修改没用。`hexo s`命令在已有public目录时会直接运行已经存在的文件，所以在已有public目录时并不会自动删除这些标签，需要删除(`hexo clean`)缓存之后重新生成才会消除。

最后感谢你的支持哈~祝使用愉快:smile:
