### ISSUE TITLE
你好！我有两个问题！！

### ISSUE THREAD

**Issue by LianZhuotao** [Siricee/hexo-theme-Chic#26]
问题1：文章底部的Author怎么设置
问题2：怎么更改页面右上方Posts，Categories等等标签的名称？？我在配置文件中修改成中文，页面可以显示中文，但这时候，点击头像无法跳转到文章页面！！不知道为什么！试了很多次发现只要改名就会出错，请问应该如何修改！

**Comment by LianZhuotao** [comment]
![image](https://user-images.githubusercontent.com/50575245/66270094-80782880-e88a-11e9-981b-0a5044596a1e.png)

**Comment by LianZhuotao** [comment]
更改后主页可以显示，但是点击头像无法再跳转文章页面了

**Comment by Siricee** [comment]
#### 回复问题1：

文章底部Author到hexo根配置文件中(你的根目录config.yml)中添加，然后到主题配置文件（Chic/_config.yml）中把`post_copyright_author_enable`字段改为true即可。

#### 回复问题2：

把`hexo-theme-Chic/layout/_page/profile.ejs`中的代码，可以点击[这里](https://github.com/Siricee/hexo-theme-Chic/blob/eaefcc3aed97f9d4780524bea61590830d73a512/layout/_page/profile.ejs#L4)看代码位置
```html
<a href="<%- url_for(theme.nav.Posts) %>"><img src="<%- url_for(theme.avatar) %>"></a>
```
改成
```html
<a href="/archives/"><img src="<%- url_for(theme.avatar) %>"></a>
```
即可。
