### ISSUE TITLE
如何在该主题中添加数学公式支持？

### ISSUE THREAD

**Issue by xzsunbest** [Siricee/hexo-theme-Chic#3]
您好！我试用了您的主题之后感觉这款主题很不错，不过好像并没有自带数学公式渲染支持，但是我在一般写作过程中数学公式支持还是非常重要的。我在尝试按照以下几篇博文教程配置均没有成功：
1. [hexo中插入数学公式](http://stevenshi.me/2017/06/26/hexo-insert-formula/)
2. [Hexo 的 Next 主题中渲染 MathJax 数学公式](https://blog.csdn.net/wgshun616/article/details/81019687)
3. [在Hexo中渲染MathJax数学公式](https://www.jianshu.com/p/7ab21c7f0674)

所以想请教以下作者如何给本主题添加数学公式支持？谢谢您~~

**Comment by Sirice19** [comment]
我觉得你说的十分有道理，数学公式的确是一个硬需求。
经过我几小时的patch，**现在Chic主题已经支持MathJax公式了**，请clone新版本的主题并根据配置文档的说明进行主题配置。

实际显示效果请见[MathJax Test | Hexo](https://sirice19.github.io/hexo-theme-Chic/2019/07/05/MathJax_test/)

如果觉得效果不错请点个star支持下！祝您使用愉快~

**Comment by Sirice19** [comment]
关于如何支持的问题我也讲下原理，这里引入了一个[MathJax](https://www.mathjax.org)外部库，会在页面加载完成后通过正则匹配解析当前页面的公式并转换为mathjax特殊格式。

你发的链接里有一些方案的作者提到更换markdown的渲染引擎，比如将hexo-renderer-marked更换为hexo-renderer-kramed，我个人不赞成这种方法，因为可能会改变markdown的书写习惯，而且新的渲染引擎可能有更多bug。因此我在不更换markdown渲染器的条件下通过外部mathjax库更新DOM来解决这个问题。

但直接引入mathjax会在每个页面都执行一次遍历正则匹配，在没有公式的页面将会大幅降低性能，所以我使用了按需加载的方式启动这个外部库。

希望可以帮到你，有什么问题可以发issue或给我Email。

**Comment by xzsunbest** [comment]
好的谢谢，辛苦您了😊😊😊
