### ISSUE TITLE
Missing tag index page

### ISSUE THREAD

**Issue by astinus87** [Siricee/hexo-theme-Chic#30]
I cloned chic theme into themes folder. Added some tags into one of the posts. Started server by running 'hexo server'. When I click the tags link in the main navbar I get the "Cannot GET /tag/" displayed at the page. The individual tag pages are displayed correctly when I click on a specific tag. So the page with -Tag Cloud- title in the demo seems to be missing in my setup. Am I missing something?

**Comment by Siricee** [comment]
Ohh, you can see document README [Add 'Tag','Category' Page](https://github.com/Siricee/hexo-theme-Chic#add-tagcategory-page).

Please remember to read README doc before you use the Chic theme.
