### ISSUE TITLE
请问如何显示浏览量？

### ISSUE THREAD

**Issue by LianZhuotao** [Siricee/hexo-theme-Chic#33]

**Comment by LianZhuotao** [comment]
<% if (theme.busuanzi && theme.busuanzi.enable && !index){ %>
        
        <span id="busuanzi_container_page_pv" style='display:none' class="<%= class_name %>">
              <i class="icon-smile icon"></i> 阅读数：<span id="busuanzi_value_page_pv"></span>次
        </span>
<% } %>
这个是我找到每个文章的阅读数统计代码，应该放到哪里？？
想让他显示在如图这一行的后面
<img width="795" alt="截屏2019-10-27下午10 19 28" src="https://user-images.githubusercontent.com/50575245/67635237-04f91c80-f908-11e9-83de-5e3e4016bf96.png">

**Comment by LianZhuotao** [comment]
<% if (theme.busuanzi && theme.busuanzi.enable && !index){ %>
        
        <span id="busuanzi_container_page_pv" style='display:none' class="<%= class_name %>">
              <i class="icon-smile icon"></i> 阅读数：<span id="busuanzi_value_page_pv"></span>次
        </span>
<% } %>

**Comment by Siricee** [comment]
放到[这里](https://github.com/Siricee/hexo-theme-Chic/blob/639ed379dbd6c60b2d5d2be721e2c2101c34c0f7/layout/_page/post.ejs#L29)
第29行后面，div结束之前
