### ISSUE TITLE
请问如何美化页面排版

### ISSUE THREAD

**Issue by yuanyimao** [Siricee/hexo-theme-Chic#35]
作者你好，我非常喜欢你这个主题，极简而且有封面。
## 问题描述  
我打算把这个做成自己的个人学术主页，于是我自己新建了一个名字叫 about的页面，然后用markdown写出来的界面如下（麻烦作者打开链接看一下about 界面）。 链接：https://yuanyimao.github.io/   
### 图片
![image](https://user-images.githubusercontent.com/54013266/68827509-30884f00-06dd-11ea-82dc-0449cd8a2041.png)  
这个排版看起来有点太朴素了/(ㄒoㄒ)/~~，我不需要什么其他功能，但不知道应该如何入手修改。比如修改字体？修改字号？调整行间距？作者能给一些建议吗？    
## 可能希望达到的效果    
![image](https://user-images.githubusercontent.com/54013266/68828184-c1602a00-06df-11ea-889c-6dba140eaf4e.png)
![image](https://user-images.githubusercontent.com/54013266/68828201-ca50fb80-06df-11ea-8e14-69cd56eed616.png)
当然也不一定非要是上面这种样子，就是能够稍微美观一点就可以了，我可能会添加我的照片，希望作者能够给一点修改的意见。非常感谢作者的辛苦努力，如果作者有其他的细节问题，我会尽快给出😀。

**Comment by Siricee** [comment]
about页面支持markdown语法和html语法，你说的改字体、改字号、行间距、加粗斜体**都可以通过markdown标签**实现。另外，本项目支持pullquote标签插件，如果你的照片以pullquote方式插入就可以实现图中的照片悬浮于文字中的效果。

具体参考 [Tag Plugins | Hexo](https://hexo.io/docs/tag-plugins#Pull-Quote) 即
```markdown
{% pullquote .right %} //.right 右侧悬浮，.left 左侧悬浮
![picture](...url of the picture)
{% endpullquote %}
```
说下我的意见，你的介绍段间距可以空两行，这样看着会更加清晰；关键词部分可以加粗斜体或下划线。

以你第一段举例，简单的修改一下：
> I am a master student in the **Department of Media and Communication** at **Shanghai Jiao Tong University**. My research interests are broadly in the area of media psychology, with a specific focus on *how an individual’s psychological processes*, other contextual factors, and exposure to media narratives shape online pro-social behavior. At the same time, I am interested in *how an individual’s potential cognitive and emotional mechanisms work*. Another topic that I am interested in *how people’s interactive behaviors influence their online social reading experiences*. I use quantitative methods (online survey; lab experiments) and analysis (SEM and HLM) combined with qualitative methods (focus group interview).

以上对应markdown语法为：
```markdown
{% pullquote .right %}
![picture](url)
{% endpullquote %}
I am a master student in the **Department of Media and Communication** at **Shanghai Jiao Tong University**. My research interests are broadly in the area of media psychology, with a specific focus on *how an individual’s psychological processes*, other contextual factors, and exposure to media narratives shape online pro-social behavior. At the same time, I am interested in *how an individual’s potential cognitive and emotional mechanisms work*. Another topic that I am interested in *how people’s interactive behaviors influence their online social reading experiences*. I use quantitative methods (online survey; lab experiments) and analysis (SEM and HLM) combined with qualitative methods (focus group interview).
```
以上仅仅为我个人意见，借此抛砖引玉。希望可以帮到你，如果觉得有帮助请点个star支持下谢谢！

**Comment by yuanyimao** [comment]
非常感谢作者的回复，我去摸索一下，非常感谢，❤️
