### ISSUE TITLE
添加链接选项

### ISSUE THREAD

**Issue by CaiXiaoBai** [Siricee/hexo-theme-Chic#37]
我如果想要添加 _config.yml 里边的 links 选项，应该怎么操作

**Comment by Siricee** [comment]
links主要影响的是图标。我用的是[阿里iconfont](https://www.iconfont.cn/)的unicode类型图标库，生成文件保存在`Chic/source/fonts/`中。

你也可以自己找第三方图标或者图片，在https://github.com/Siricee/hexo-theme-Chic/blob/639ed379dbd6c60b2d5d2be721e2c2101c34c0f7/layout/_page/profile.ejs#L15 这里引入就可以了

**Comment by YuanLiChenAi** [comment]
能举个例子嘛，还是没看懂怎么自定义链接选项😣

**Comment by Siricee** [comment]
> 能举个例子嘛，还是没看懂怎么自定义链接选项😣

你上阿里iconfont网站，选择你需要的图标，然后保存为项目，打包下载，下载的zip里会包含一堆什么svg、字体等文件，你把这一堆文件放在`Chic/source/fonts/iconfont`下，在source/css/style.styl中引入主css (iconfont css已经包含其他外部资源)
就像已经存在的那一行
```css
// icon
@import "../fonts/iconfont/iconfont.css"
```
然后根据你下载的图标的类名（一般来说是`icon-xxx`格式）添加到config.yml中，添加时只写`xxx`部分即可。

到这步你就可以像使用主题原来自带的图标一样使用主题了。

**Comment by brandon0824** [comment]
你好 你的主题很好看 用了你的主题也遇到了上述的问题
我也是去iconfont上找的一套图标 但是发现你写了icon-xxx然后在config.yml直接引入xxx
我想知道如何将代码改成直接用那个symbol的全名
例如 引入你的rss图标 就直接在config.yml中引入icon-rss
因为我的图标是iconRss 没有一横

**Comment by Siricee** [comment]
补充：关于自定义首页图标详细操作示例请看 #69 的问题1
