### ISSUE TITLE
Archive页ejs报错

### ISSUE THREAD

**Issue by GaryKnows** [Siricee/hexo-theme-Chic#39]
- hexo new page archive
- 在_config.yml中nav加入Archive: /archive
- //source/archive/index.md 加入layout: archive
- hexo s --debug
- 点击Archive

Error:
```
    1| <div class="post-wrap archive">
    2|     <% var last_year = ''; %>
>>  3|     <% page.posts.each(function (post) { %>
    4|         <% var cur_year = post.date.year(); %>
    5|
    6|         <% if(last_year !== cur_year){ %>

Cannot read property 'each' of undefined
```

**Comment by Siricee** [comment]
> * 在_config.yml中nav加入Archive: /archive

改成 Archive: /archives 
路径要和layout中的ejs模板文件名一致。
