### ISSUE TITLE
Hide the checkbox in the upper right corner

### ISSUE THREAD

**Issue by chenwpop** [Siricee/hexo-theme-Chic#4]
Hi, I love this theme.
But in the latest version chrome, there is a checkbox in the upper-right corner, so I add a `hidden` tag in the *header.ejs* to remove it.
If you don't add it intentionally, please take a look and remove it XD!

**Comment by Siricee** [comment]
Thanks for your support!
I just tested on Chrome 75.0.3770.100, but did not find the error you said....
But this is a definately potential question ,I will maintain to track the question you mentioned.

Thank you for your advise!:smile:
