### ISSUE TITLE
在/_config.yml 文件更改语言，不起效果主题依然是英文的

### ISSUE THREAD

**Issue by Young-Lei** [Siricee/hexo-theme-Chic#40]
我在配置文件中更改了语言，名称都对应上了，但是不起效果

**Comment by Siricee** [comment]
复制一下你的config文件

**Comment by Young-Lei** [comment]
> 复制一下你的config文件

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Young's personal website
subtitle: Welcome 
description: 欢迎来到我的网站
keywords: iOS 生活 工作
author: Young Lei
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: chic

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/Young-Lei/Young-Lei.github.io.git
  branch: master

**Comment by Siricee** [comment]
哦 你说的是hexo全局config吧，本主题不支持多语言，可以在主题config中用中文。

**Comment by Siricee** [comment]
https://github.com/Siricee/hexo-theme-Chic/issues/29 已经提到过。

**Comment by Young-Lei** [comment]
> 哦 你说的是hexo全局config吧，本主题不支持多语言，可以在主题config中用中文。

在主题config中用中文，这个意思值得是主题会变成中文的么？请教一下如何设置呀

**Comment by Siricee** [comment]
## 页面更改中文方案
### category、tag页面更改中文
在source\category\index.md中修改title
![image1](https://user-images.githubusercontent.com/25154957/69595580-f3a44c80-103a-11ea-9e83-c208722fd1a3.png)
### 页面导航栏更改中文
直接在config中写中文就行
![image2](https://user-images.githubusercontent.com/25154957/69595658-1e8ea080-103b-11ea-8ac9-26ae36270f94.png)
### 网站title更改中文
在 https://github.com/Siricee/hexo-theme-Chic/blob/639ed379dbd6c60b2d5d2be721e2c2101c34c0f7/layout/category.ejs#L29 这里
![image3](https://user-images.githubusercontent.com/25154957/69595694-3534f780-103b-11ea-9328-36a296750cf0.png)
把英文改成中文即可。
