### ISSUE TITLE
How to custom the tags page layout?

### ISSUE THREAD

**Issue by DocNan** [Siricee/hexo-theme-Chic#45]
Dear Siricee, 
I am very happy with your Chic theme. However, recently I met with some problems with it. I try to create a new page with tags and its belonging blogs hyperlinks like that in Aath theme. What I current get is this style effect:      https://docnan.github.io/tags/
It is ugly with all the tabs align to the very left side. How do I change the layout of this page? I am new to htlm/css web page designing. Do you have any suggestions?
Thanks very much! 

Nan

**Comment by Siricee** [comment]
oh, it seems that your content in HTML is correct, what you need to do is just add some style sheet. you can refer to [archive style](https://github.com/Siricee/hexo-theme-Chic/blob/master/source/css/_page/archive.styl), you can reuse this style sheet.
