### ISSUE TITLE
手机dark模式异常

### ISSUE THREAD

**Issue by lytw13** [Siricee/hexo-theme-Chic#46]
手机上将主题更改成dark模式时，会出现短暂的light模式闪屏现象。

**Comment by Siricee** [comment]
感谢您的反馈，这个问题是刷新页面到读取localstorage变量执行函数的时间空挡太长引起的，确实存在这个现象，而且我目前没有较好的解决办法。。等我后续学习知道怎么优化这个时间之后就会尽力修复。
