### ISSUE TITLE
想为主题写一个首页

### ISSUE THREAD

**Issue by childtclx** [Siricee/hexo-theme-Chic#48]
想和作者聊聊可以吗，我是刚踏入计算机领域的小白，希望能从作者那得到帮助，我真的喜欢这个主题，但是又想让它有首页和搜索功能。

**Comment by Siricee** [comment]
可以的，昨天太忙没来得及回复。。

你说的首页是什么意思呢，我这个主题已经做了封面了，不知道你说的首页和封面是不是一个意思。
搜索功能可以使用hexo的插件，在[主页-插件](https://hexo.io/plugins/)上可以安装，比如 [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)，但我不在初始化时添加这个功能有我设计的理由，可以看这里 https://github.com/Siricee/hexo-theme-Chic/issues/2 。

博客重点是内容，如果你想练习前端技能可以自行尝试，但我在设计的角度不会提供相关功能的直接支持。

最后感谢你的支持，如果喜欢本主题请点个star 谢谢

**Comment by childtclx** [comment]
首页，就是主题加部分文章内容显示



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liu Zijian <notifications@github.com&gt;
发送时间: 2020年1月10日 13:34
收件人: Siricee/hexo-theme-Chic <hexo-theme-Chic@noreply.github.com&gt;
抄送: childtclx <820468902@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Siricee/hexo-theme-Chic] 想为主题写一个首页 (#48)




Closed #48.

**Comment by Siricee** [comment]
是类似于[这种](https://github.com/saberland/create-portfolio)吗，可以的，你需要什么帮助

**Comment by childtclx** [comment]
是的，我们能加WeChat聊吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liu Zijian <notifications@github.com&gt;
发送时间: 2020年1月10日 14:18
收件人: Siricee/hexo-theme-Chic <hexo-theme-Chic@noreply.github.com&gt;
抄送: childtclx <820468902@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Siricee/hexo-theme-Chic] 想为主题写一个首页 (#48)

**Comment by Siricee** [comment]
wechat-18846428543，添加请备注
