### ISSUE TITLE
标题中添加代码大小将不一致

### ISSUE THREAD

**Issue by SilhDing** [Siricee/hexo-theme-Chic#49]
如果在h1,h2,h3,h4,h5标题中添加inline code，code的大小无法和标题大小一致。

![image](https://user-images.githubusercontent.com/35630701/72201034-ef1ce180-348a-11ea-8229-2cc7443f87d5.png)

可以在`css/_page/_post/post_code.styl`里`.post-content`下添加
```css
h1,h2,h3,h4,h5
    code
      font-size inherit
```
解决
![image](https://user-images.githubusercontent.com/35630701/72201044-fe039400-348a-11ea-8439-dd3ee84e8708.png)

同样的， 要是在list里面使用inline code可能也会出现问题，我也是手动添加了大小配置。

**Comment by Siricee** [comment]
建议已采纳，谢谢您的支持！
