### ISSUE TITLE
关于文章标题 markdown语法 “##”关键字创建的标题，为什么渲染后的页面还会出现“#”？

### ISSUE THREAD

**Issue by langkexiansheng** [Siricee/hexo-theme-Chic#5]
如题

**Comment by Siricee** [comment]
> 如题

没有看懂，请详细描述您的问题。

**Comment by langkexiansheng** [comment]
![image](https://user-images.githubusercontent.com/37947784/60969837-28955880-a353-11e9-808e-e5a81a77a0ed.png)
就是图片中圈出来的地方，这个井号本应该是md语法里标题的标记符，生成html页面后就没了的，这还还是出现了。

**Comment by Siricee** [comment]
> ![image](https://user-images.githubusercontent.com/37947784/60969837-28955880-a353-11e9-808e-e5a81a77a0ed.png)
> 就是图片中圈出来的地方，这个井号本应该是md语法里标题的标记符，生成html页面后就没了的，这还还是出现了。

这是我主题的h1、h2级标题样式，加上一个前缀符可以区分出标题和正文。如果你不需要可以在CSS中`Chic\source\css\_page\_post\post_content.styl`中删除。
祝您使用愉快！

**Comment by Siricee** [comment]
补充：具体删除该符号方法

在CSS中Chic\source\css\_page\_post\post_content.styl中删除。
具体请删除这里（删除content后面的内容即可）

![pic](https://user-images.githubusercontent.com/25154957/65613796-1c7f7580-dfe9-11e9-9e3b-b98cd7a3b61a.png)

**Comment by difengJ** [comment]
按照上述方式修改后，
hexo clean 
hexo g
hexo d
但是还是存在#。
<img width="305" alt="Screen Shot 2020-01-11 at 4 36 08 PM" src="https://user-images.githubusercontent.com/19460327/72201583-a49e6380-3490-11ea-8f5f-dc89a3c4595d.png">
求助

**Comment by Siricee** [comment]
回复 @difengJ 浏览器有缓存，按shift+f5试试
