### ISSUE TITLE
关于头像图片的问题

### ISSUE THREAD

**Issue by mengyu666** [Siricee/hexo-theme-Chic#53]
您好，我有几个问题想向你请教一下。
1.我修改了主页头像，并把头像文件放在themes\Chic\source\image目录下，但头像加载过慢甚至有时候会出现头像加载失败，想请问一下该怎么解决，谢谢:)
2.能不能在posts categories tags about 上再加上别的，比如说photos，pictures等，谢谢。

**Comment by Siricee** [comment]
1. 没得解决。由于众所周知的原因，你放在github pages上就要做好速度慢的觉悟。改善的话可以部署在国内gitee上或给静态资源加上CDN服务。
2. 可以，新建页面即可，参考hexo文档，使用`hexo new page photos`新建photos页面。
