### ISSUE TITLE
关于支持 Font Awesome & GitHub Emoji

### ISSUE THREAD

**Issue by FatBobGo** [Siricee/hexo-theme-Chic#59]
请问可以支持Font Awesome 图标吗？

`<i class="fa fa-tag"></i>`

**Comment by FatBobGo** [comment]
请问可以支持github emoji吗?  例如 :+1: 

https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#using-emoji

**Comment by Siricee** [comment]
> 请问可以支持Font Awesome 图标吗？
> 
> `<i class="fa fa-tag"></i>`

可以支持。

- 方法1：在线引入
  使用font-awesome提供的cdn服务，官网是发送邮件方式，会给你一个`<script>`链接，你复制到`Chic\layout\_partial\head.ejs`中即可使用。
- 方法2：本地引入
  下载zip文件，将css、fonts文件夹拷贝到source文件夹新建文件夹font-awesome中，然后到`Chic\source\css\style.styl`中`@import "../font-awesome/font-awesome.min.css"`即可使用。

**Comment by Siricee** [comment]
> 请问可以支持github emoji吗? 例如 👍
> 
> https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#using-emoji

github官方emoji我<del>嫌麻烦</del>没有研究具体怎么支持，但我自己的博客用的是这个库：https://ionicabizau.github.io/emoji.css/ 只需要添加css就可以，在style.styl里导入，然后按他的库中说明的标记使用即可，大部分emoji也够用了。

如果你觉得不够用的话可以去npm上搜一下github-emoji相关包，按说明文档安装使用就可以了。

还有什么问题请在issue中提出。如果有帮到你的话请点个star支持一下谢谢！

**Comment by FatBobGo** [comment]
> > 请问可以支持Font Awesome 图标吗？
> > `<i class="fa fa-tag"></i>`
> 
> 可以支持。
> 
> * 方法1：在线引入
>   使用font-awesome提供的cdn服务，官网是发送邮件方式，会给你一个`<script>`链接，你复制到`Chic\layout\_partial\head.ejs`中即可使用。
> * 方法2：本地引入
>   下载zip文件，将css、fonts文件夹拷贝到source文件夹新建文件夹font-awesome中，然后到`Chic\source\css\style.styl`中`@import "../font-awesome/font-awesome.min.css"`即可使用。

感谢提供思路。
1. 新建文件夹 `Chic/source/font-awesome`
1. 把下载好的font-awesome中的2个文件夹`css`, `fonts`拷贝到刚刚创新的文件夹
1. 在`Chic\source\css\style.styl`添加
`@import "../font-awesome/**css**/font-awesome.min.css"`
1. 在文章中引用图片
`<i class="fa fa-thermometer-full" aria-hidden="true"></i>`

重启服务之后，我发现html页面生成了正确的标识，但是就是不能显示图标。请问是什么原因？

**Comment by Siricee** [comment]
我之前回复的方法2有问题，直接import到style.styl中会导致路径错误。

正确方法在之前的issue中重新编辑了。

这里也重新发一下：

- 方法2：本地引入
  下载zip文件，将css、fonts文件夹拷贝到source文件夹新建文件夹font-awesome中。然后在`Chic/_config.yml`中style字段加入以下内容
```yaml
stylesheets:
  - /css/style.css
  - /font-awesome/css/font-awesome.css # 引入font-awesome
```
即可使用`<i>`标签引入图标。

本方法测试已通过。

**Comment by FatBobGo** [comment]
成功！感谢你！
