### ISSUE TITLE
安装主题后执行 hexo g 命令报错

### ISSUE THREAD

**Issue by qinyuanpei** [Siricee/hexo-theme-Chic#6]
安装主题后，执行hexo g命令报以下错误：
![image](https://user-images.githubusercontent.com/7688258/61458485-35dac480-a99d-11e9-8217-455dbedc07c2.png)

能告知下是什么原因吗？貌似是EJS模板文件语法的问题

**Comment by Siricee** [comment]
应该是你拷贝文件的时候碰到backspace键了吧，我的源文件是（注意有个#号这是ejs中注释的标签）
```javascript
<%# mobile %>
```
如果另外出现其他类似问题请重新git clone。祝您使用愉快。
