### ISSUE TITLE
hexo-generator-index-pin-top实效

### ISSUE THREAD

**Issue by FatBobGo** [Siricee/hexo-theme-Chic#60]
你好，我想把文章置顶。通过安装测试插件`hexo-generator-index-pin-top`后，发现并没有生效。

请问这个是哪里有特殊处理了？

```
$ npm uninstall hexo-generator-index --save
$ npm install hexo-generator-index-pin-top --save
然后在文字顶部添加 top: true;
```

**Comment by Siricee** [comment]
FrontMatter中不需要写分号，直接写`top: True`即可。
但这是语法层面的问题，我没有测试这个插件，但理论上应该是支持的，因为文章列表我用的也是默认日期排序函数。
如果实际上不能支持那说明这个插件与我的主题并不能兼容，我会后续看反馈意见的多少，在以后更新中修复这个问题。

**Comment by FatBobGo** [comment]
多种写法我已经测试过，请帮忙修复。因为我觉得置顶功能挺实用的。感谢。

请问有交流群吗？这样可以减少很多issues？

**Comment by Siricee** [comment]
关于hexo-generator-index的问题，我在开发Chic主题时对文章排序并没有用到root下的config中`index_generator`这个字段。

这个字段是landscape官方主题中对首页(直接是文章列表)的排序和分页，Chic的首页是一个封面而不是文章列表，所以没有用到这个字段，因此你会发现，在Chic主题中这个字段其实不管你填什么都是无效的，也就是说，替换hexo-generator-index插件为带有置顶功能的插件并不会解决这个问题。

我查了一下找到了这个文章供参考：[解决Hexo置顶问题 | Netcan_Space](http://www.netcan666.com/2015/11/22/%E8%A7%A3%E5%86%B3Hexo%E7%BD%AE%E9%A1%B6%E9%97%AE%E9%A2%98/)

你可以试一下，我没有测试。如果不好使的话暂时也只能这样，如果没有设计的修改可能会破坏原来的代码结构，因此未来可能在更新中修复这个问题，如果你有解决办法测试通过后也可以回到这个issue中发一下，如果方案可行即可采纳。

另外，本主题暂时没有交流群，全部是由我一人维护，所有issue也由我回复，有问题可以提issue或者给我发email。

**Comment by FatBobGo** [comment]
> 关于hexo-generator-index的问题，我在开发Chic主题时对文章排序并没有用到root下的config中`index_generator`这个字段。
> 
> 这个字段是landscape官方主题中对首页(直接是文章列表)的排序和分页，Chic的首页是一个封面而不是文章列表，所以没有用到这个字段，因此你会发现，在Chic主题中这个字段其实不管你填什么都是无效的，也就是说，替换hexo-generator-index插件为带有置顶功能的插件并不会解决这个问题。
> 
> 我查了一下找到了这个文章供参考：[解决Hexo置顶问题 | Netcan_Space](http://www.netcan666.com/2015/11/22/%E8%A7%A3%E5%86%B3Hexo%E7%BD%AE%E9%A1%B6%E9%97%AE%E9%A2%98/)
> 
> 你可以试一下，我没有测试。如果不好使的话暂时也只能这样，如果没有设计的修改可能会破坏原来的代码结构，因此未来可能在更新中修复这个问题，如果你有解决办法测试通过后也可以回到这个issue中发一下，如果方案可行即可采纳。
> 
> 另外，本主题暂时没有交流群，全部是由我一人维护，所有issue也由我回复，有问题可以提issue或者给我发email。

你好，我发issue之前测试过 Netcan_Space。然而并不好用。
请问你知道背后渲染的逻辑吗？我看了以下插件的逻辑，没有看到出有什么异常阿。

**Comment by Siricee** [comment]
不知道。文章列表是直接按日期进行排序遍历出来的，根本用不到`index_generator`，所以我也不懂这个变量正确用法是什么

**Comment by FatBobGo** [comment]
我参考文章把原生的`node_modules/hexo-generator-index/lib/hexo-generator-index.js`修改后，还是不行。

```
'use strict';

var pagination = require('hexo-pagination');

module.exports = function(locals) {
  var config = this.config;
  var posts = locals.posts.sort(config.index_generator.order_by);

  posts.data = posts.data.sort(function(a, b) {
      if(a.top && b.top) {
          if(a.top == b.top) return b.date - a.date;
          else return b.top - a.top;
      }
      else if(a.top && !b.top) {
          return -1;
      }
      else if(!a.top && b.top) {
          return 1;
      }
      else return b.date - a.date;
  });

  var paginationDir = config.pagination_dir || 'page';

  return pagination('', posts, {
    perPage: config.index_generator.per_page,
    layout: ['index', 'archive'],
    format: paginationDir + '/%d/',
    data: {
      __index: true
    }
  });
};
```

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
