### ISSUE TITLE
Google adsense不生效

### ISSUE THREAD

**Issue by FatBobGo** [Siricee/hexo-theme-Chic#66]
先生你好，

请问一下，为什么google提示说我的gogole ad并不活跃？我已经把<script>添加在网站了。

[blog](https://fatbobgo.github.io/)

**Comment by Siricee** [comment]
1. 请检查你的站点是否正确添加了脚本。
2. 你的网站如果没有几个不同IP的用户点开的话必然不活跃；另外google ads会被各种广告拦截插件拦截。
3. 与主题无关的问题尽量不要在这里问，谢谢合作
