### ISSUE TITLE
Latex无法显示百分号

### ISSUE THREAD

**Issue by yiloo** [Siricee/hexo-theme-Chic#67]
已经在_config.yml中开启mathjax，并且在文章头加入`mathjax: true`。在latex中使用百分号无法正常显示出来

下面这些latex语句都无法显示
```
$\%$ 
 
or

$$ \% $$
```

我的环境
hexo: 3.9.0
hexo-cli: 3.1.0
os: Darwin 19.3.0 darwin x64
node: 13.8.0
v8: 7.9.317.25-node.28
uv: 1.34.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
Chic: v1.0.0-5-g3513633

**Comment by Siricee** [comment]
你好，这个问题是html渲染先于LaTeX插件渲染造成的，在html渲染阶段，反斜杠`\`会被当做转义符号，而正确输出反斜杠需要再次转义，也就是`\\`。

因此这个问题，百分号前面需要加2个反斜杠`\\%`，在html中才会显示为'\%'，LaTeX才会显示为`%`。

```
$\\%$ 
or
$$ \\% $$
```
