### ISSUE TITLE
关于图标iconfont的疑惑

### ISSUE THREAD

**Issue by mengyu666** [Siricee/hexo-theme-Chic#69]
您好，如果我想将那个iconfont图标改成我喜欢的话，我不是只要从阿里图标库看上我喜欢的并且打包成项目，然后将这个压缩包下载并解压缩，并用里面的文件将原先themes\Chic\source\fonts\iconfont里文件替换。但我这样做，刷新并且清除缓存，图标依旧没有改变，请问我有哪里操作不当的地方吗？谢谢。

另：一级标题，二级标题前的*我按照您以前在issue里说的方法改掉，刷新并且清除缓存，依旧没有发生任何变化，想请问您我还该做些什么，谢谢。

**Comment by Siricee** [comment]
### 问题1
> 您好，如果我想将那个iconfont图标改成我喜欢的话，我不是只要从阿里图标库看上我喜欢的并且打包成项目，然后将这个压缩包下载并解压缩，并用里面的文件将原先themes\Chic\source\fonts\iconfont里文件替换。但我这样做，刷新并且清除缓存，图标依旧没有改变，请问我有哪里操作不当的地方吗？谢谢。

不要替换，替换的话可能会造成原有图标丢失。直接增加即可

操作示例：
1. 你下载的压缩包解压之后可以得到一个iconfont文件夹，这里命名为iconfont2放在`Chic/source/fonts`下（此时路径为`Chic/source/fonts/iconfont2`）
2. 然后在`source/css/style.styl`中引入主css (iconfont css已经包含其他外部资源)
就像已经存在的那一行
```css
// icon
@import "../fonts/iconfont/iconfont.css"  // 原来的
@import "../fonts/iconfont2/iconfont.css"  // 你新增的
```
然后根据你下载的图标的类名（一般来说是icon-xxx格式）添加到config.yml中，添加时只写xxx部分即可。
举例，你的iconfont2中添加了icon-AABB
```yaml
# config.yml文件
links:
  Blog: /archives
  AABB: url #新增的图标
```

### 问题2
> 另：一级标题，二级标题前的*我按照您以前在issue里说的方法改掉，刷新并且清除缓存，依旧没有发生任何变化，想请问您我还该做些什么，谢谢。

这个问题操作过程看这个 https://github.com/Siricee/hexo-theme-Chic/issues/5 
你说的两个问题在刷新后页面都没变化，可能是浏览器有缓存，按shift+F5刷新页面试试，还有的话执行`hexo clean`、`hexo g` 然后再次刷新缓存。

**Comment by mengyu666** [comment]
你好
![屏幕截图(201)](https://user-images.githubusercontent.com/58378454/77837704-c6111080-719e-11ea-8fb6-e80003d1904d.png)
您这里所说的类名是在哪里寻找亦或是指什么？
您这里AABB：url 中url我是要添加某一个链接吗，还是只需要写url即可。
谢谢。
另：这个换iconfont是不是就是把你原先所带的 正六边形中间有个H的那个图形换掉？
谢谢。

**Comment by Siricee** [comment]
你下载的 iconfont 包中会有一个 demo_index.html 的文件，这个文件展示下载的全部图标的三种格式，切换到 font class 下每个图标会有一个 class 名，这个就是图标的类名。如图
![pic](https://user-images.githubusercontent.com/25154957/77840559-886eb080-71bb-11ea-882c-524bdb60c4f8.png)

url 是你要添加的链接，内部链接或外部链接都可以，**具体格式请参考示例代码**。

另，“正六边形中间有个H的那个图形” 这个是 favicon ，**请提问前看清文件名**。

**Comment by mengyu666** [comment]
好的，谢谢作者的耐心解答。
那我换favicon是不是也跟上面的方法是一样的？
还有我参照以前issue中把网易云的iframe插件放到博客博文所在的markdown文件中，会破坏所在博文的内容，这是为啥？会不会是我这个插件放错地方了？
谢谢。

**Comment by Quetweilan** [comment]
请问下我已按照操作
1. 在阿里图标下载代码。
2. 解压，更名为font_person。拷贝至source/fonts文件夹。
3. 在style.styl 添加代码 @import "../fonts/font_person/iconfont.css"
4. 在font_person 里的iconfont.css 里改图标
.icon-telegram:before {
  content: "\e8db";
}
这里在demo_index里telegram & content都是对应的
5. 问题： 
 在config文件里添加  telegram: url 不显示图标，但是手机上能看到一个未加载的图标，点进去链接是正确的

**Comment by Siricee** [comment]
> 请问下我已按照操作
> 
> 1. 在阿里图标下载代码。
> 2. 解压，更名为font_person。拷贝至source/fonts文件夹。
> 3. 在style.styl 添加代码 @import "../fonts/font_person/iconfont.css"
> 4. 在font_person 里的iconfont.css 里改图标
>    .icon-telegram:before {
>    content: "\e8db";
>    }
>    这里在demo_index里telegram & content都是对应的
> 5. 问题：
>    在config文件里添加  telegram: url 不显示图标，但是手机上能看到一个未加载的图标，点进去链接是正确的

不需要有第4步，直接跳过第4步即可。iconfont的css每个对应都是有逻辑的，不要改下载下来的代码。

**Comment by Quetweilan** [comment]
> > 请问下我已按照操作
> > 
> > 1. 在阿里图标下载代码。
> > 2. 解压，更名为font_person。拷贝至source/fonts文件夹。
> > 3. 在style.styl 添加代码 @import "../fonts/font_person/iconfont.css"
> > 4. 在font_person 里的iconfont.css 里改图标
> >    .icon-telegram:before {
> >    content: "\e8db";
> >    }
> >    这里在demo_index里telegram & content都是对应的
> > 5. 问题：
> >    在config文件里添加  telegram: url 不显示图标，但是手机上能看到一个未加载的图标，点进去链接是正确的
> 
> 不需要有第4步，直接跳过第4步即可。iconfont的css每个对应都是有逻辑的，不要改下载下来的代码。

刚刚重新在网站打包下载了一份新图标。
前3步没有改变（后来也尝试过解压后文件夹名字不改，无区别）
第四步没有改代码，只是确认了名字是telegram 和 email
在第5步添加后仍不显示 quetweilan.github.io
