### ISSUE TITLE
文章索引遮挡住了文章内容

### ISSUE THREAD

**Issue by Mrliuxchn** [Siricee/hexo-theme-Chic#7]

**Comment by Siricee** [comment]
能告知一下您的屏幕分辨率吗

**Comment by Siricee** [comment]
我设置的索引宽度是最低1279px为了适配最低1280\*800低分屏幕，小于这个值索引部件会隐藏。另外浏览器缩放比例全部是按100%适配，通过了1366\*768标准屏幕和1920\*1080UHD屏幕测试。

如果你的屏幕宽度为1280-1290px之间可能会出现索引遮挡问题，请将屏幕调整至100%缩放（键盘快捷键ctrl+0）

我个人认为这个问题暂时不应该在源码中修改。如果您需要自行更改请修改[这里](https://github.com/Siricee/hexo-theme-Chic/blob/6080814e60887f8c01fe9e789d7b731ac25b8699/source/css/media.styl#L170)的数值为您的最低宽度。
