### ISSUE TITLE
pdf加载

### ISSUE THREAD

**Issue by xinys** [Siricee/hexo-theme-Chic#71]
请问pdf的加载怎么操作？
我按网上查到的操作先$ npm install --save hexo-pdf安装插件再在文章里面插入pdf链接，但是打开之后文章还是显示空白。请作者不吝赐教。

**Comment by Siricee** [comment]
请先检查你的 pdf 文件路径是否正确。如果有报错信息的话也贴一下

**Comment by xinys** [comment]
md文件中的pdf链接是这样的：
外部链接：
{% pdf https://github.com/xinys/storage/blob/master/test.pdf %}
本地连接：
{% pdf ./test.pdf %}
但是网页打开之后显示空白：
![image](https://user-images.githubusercontent.com/52726041/78345770-ae87bc80-75d0-11ea-924b-22a211a20530.png)
