### ISSUE TITLE
如何加入github仓库引用

### ISSUE THREAD

**Issue by edmundwsy** [Siricee/hexo-theme-Chic#77]
请问 https://siricee.github.io/hexo-theme-Chic/2019/06/05/backreview_hexo_theme_Chic/  中，对于 Github 仓库的引用是如何加入的？需要编辑怎样的引用块才能实现类似的效果？

![image](https://user-images.githubusercontent.com/44539400/80915044-68488900-8d47-11ea-9ca4-5b46b0340b32.png)

**Comment by Siricee** [comment]
这个其实不是引用，我是用这个库
nwtgck/gh-card: GitHub Repository Card for Any Web Site
https://github.com/nwtgck/gh-card
生成的，具体操作你一看就懂了

**Comment by edmundwsy** [comment]
Thanks!!
