### ISSUE TITLE
关于字体的添加

### ISSUE THREAD

**Issue by ganwt** [Siricee/hexo-theme-Chic#78]
作者你好，
感恩制作了此主题。
这个主题很漂亮，很好用。

我在使用中遇到了日语字体不能好好显示的问题，
请问，该如何添加或者更换字体呢？

再次感谢制作了这主题。
以上

祝你身体健康。

**Comment by ganwt** [comment]
问题补充，macOS系统下，Safari浏览器正常。Chrome浏览器异常。

**Comment by Siricee** [comment]
你好，更换字体请参考https://github.com/Siricee/hexo-theme-Chic/issues/15

另外日语字体异常的问题能不能贴个异常表现截图上来，谢谢你哈。

如果是日语字体不能以设定字体显示而是用系统默认字体替换的问题，说明我首选的字体库没有包含日文编码，自行更改即可。

**Comment by ganwt** [comment]
感谢回复。以下是 **macOS Catalina 10.15.4** 版本下，Chrome浏览器中日语字体异常截图。

Chrome中显示异常 标题页

![スクリーンショット 0002-05-30 8.03.09](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfa3xde5t0j31gu0ieju0.jpg)

Safari中显示结果是正常 标题页

![スクリーンショット 0002-05-30 8.03.24](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfa3yora2qj31dc0gaacd.jpg)

Chrome 文章内容异常 截图

![スクリーンショット 0002-05-30 8.04.10](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfa408obc3j317o0u0adp.jpg)

Safari 文章内容正常 截图

![スクリーンショット 0002-05-30 8.04.03](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfa40nav8mj31850u0q6o.jpg)

我自己尝试更改`/Users/g/ganwt.com/ganwt.github.io/themes/Chic/source/css/font.styl` 

```stylus
// 非衬线体 方正兰亭
// @font-face
//   font-family 'lanting'
//   src: url('../fonts/lanting/lanting.eot'); /* IE9 */
//   src: url('../fonts/lanting/lanting.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('../fonts/lanting/lanting.woff2') format('woff2'),
//           url('../fonts/lanting/lanting.woff') format('woff'),
//           url('../fonts/lanting/lanting.ttf') format('truetype'); /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
//   font-weight 300
//   font-display swap

$font-family = arial, sans-serif;
// $font-family = 'Microsoft Jhenghei',Lantinghei SC, 'lanting', PingFang SC, Seguo UI, Microsoft Yahei, Arial, Helvetica, sans-serif;
```

并未奏效。为这种事情困扰，真是抱歉，望解答。
