### ISSUE TITLE
如何添加博客评论以及访客数目统计? 

### ISSUE THREAD

**Issue by nxu96** [Siricee/hexo-theme-Chic#8]
非常喜欢这款主题, 为您点赞. 
我在尝试自己添加 Disqus 的评论模块,但是对前端一窍不通的小白感觉有点困难. 
不知道您有没有计划添加博客评论/访客统计? 或者能不能给一个大致的指导? 非常感谢

**Comment by Siricee** [comment]
你好，首先感谢你的支持哈:smile:

我暂时没有添加博客评论系统和访客统计组件的计划，我个人认为这两个功能属于博客系统的非必要功能，秉持'**Less is More**'的设计理念，主题暂时不提供统一支持。

如果你想添加这两个功能可以自行添加。Disqus指导可以看这个：[为 Hexo 主题添加评论模块](http://moxfive.xyz/2016/01/02/hexo-comments/)，访客统计可以看下这个文章：[不蒜子 | 不如](http://ibruce.info/2015/04/04/busuanzi/)。以上功能也有其他类似的组件可以使用，请自行查阅相关教程。

祝您使用愉快。

**Comment by nxu96** [comment]
Thanks! 按照这个Disqus指导已经添加了评论功能
