### ISSUE TITLE
关于代码高亮

### ISSUE THREAD

**Issue by cmwode** [Siricee/hexo-theme-Chic#81]
不管使用什么高亮主题，代码一直是红色的，只是背景在变:
![image](https://user-images.githubusercontent.com/42599739/83044163-663bc680-a076-11ea-96f3-46c1912fe390.png)

**Comment by Siricee** [comment]
呃 感觉你这个是代码格式问题，如果是文中单独的代码块，推荐使用单个反引号 `code`(写法 \`code\`)；代码段推荐使用3个反引号
```
function(){
       console.log("hello");
}

// ```
// function(){
//       console.log("hello");
// }
// ```
```

**Comment by MagicStarLIN** [comment]
这个问题你可以尝试去除_config.yml中关于highlight的配置（是hexo自己的config不是theme里的）
```
# highlight:
#   enable: false
#   line_number: true
#   auto_detect: false
#   tab_replace: ''
#   wrap: true
#   hljs: false
```
