### ISSUE TITLE
English words with apostrophe not rendered correctly.

### ISSUE THREAD

**Issue by hakcat** [Siricee/hexo-theme-Chic#83]
Hi this is an issue I noticed:
In blog posts, words having an apostrophe (') . Ex. "They've" is not rendered completely.
It is rendered like They' {big blank space}  ve.
Please fix this?

**Comment by Siricee** [comment]
It seems that the question is caused by font. 
Issue https://github.com/Siricee/hexo-theme-Chic/issues/16 may be helpful to you.

Please contact me if you have any other questions.
