### ISSUE TITLE
［建议］ 将主题配置另外保存在 source 文件夹

### ISSUE THREAD

**Issue by AnotiaWang** [Siricee/hexo-theme-Chic#86]
这样便于编辑和Git备份
例如，我的博客文件夹是"Blog", 就在 "Blog/source/_data/" 新建一个 Chic.yml ，Hexo在生成的时候会优先读取source文件夹里的这个配置
这样在Pull新的版本时不会影响旧的配置，也方便对比、增减

**Comment by Siricee** [comment]
很好的建议 :thumbsup:

**Comment by AnotiaWang** [comment]
> 很好的建议 :thumbsup: 

我又找了找，文档在这 https://hexo.io/docs/data-files.html

![Ndx9MD.jpg](https://s1.ax1x.com/2020/06/24/Ndx9MD.jpg)

**Comment by stevenjoezhang** [comment]
Hexo 官方实现了，升级到 Hexo 5 之后使用 `_config.chic.yml` 即可
