### ISSUE TITLE
Categories只有小分类下面由内容，总的页面空白

### ISSUE THREAD

**Issue by SeikoSrp** [Siricee/hexo-theme-Chic#89]
![image](https://user-images.githubusercontent.com/32760221/89753766-1b293f80-db0c-11ea-8fa1-f2f80fdbbebb.png)
比如内网安全分类下有上面的内容

![image](https://user-images.githubusercontent.com/32760221/89753808-3d22c200-db0c-11ea-81e5-b8da9a808b25.png)
总的这个分类页面下是空白

如何做成您的demo里这种形式呢？
![image](https://user-images.githubusercontent.com/32760221/89753822-50359200-db0c-11ea-88cb-d661fa76d910.png)

**Comment by Siricee** [comment]
请阅读 [文档](https://github.com/Siricee/hexo-theme-Chic/blob/master/README-CN.md#添加tagcategory页面) 里面有详细步骤。
