### ISSUE TITLE
在此主题基础上，可否添加个相册/画廊模块？

### ISSUE THREAD

**Issue by kakarrot0109** [Siricee/hexo-theme-Chic#90]
最好是流布局 横向图片和纵向图片自适应

**Comment by Siricee** [comment]
可以用 jquery 的图片插件实现。但我个人觉得这个东西目前主流浏览器都可以右键打开图片，移动端也有长按查看图片功能，我自己原生集成进去这个功能似乎没什么很紧迫的必要。
