### ISSUE TITLE
link图标显示不全

### ISSUE THREAD

**Issue by dihambo** [Siricee/hexo-theme-Chic#92]
不知道为什么，开启GitHub或者其他一些的link开关但是不会显示图标，html里会有这个link的<a>标签但是不会加载图标，就很奇怪。跟位置也没关系，换了位置也没办法。

**Comment by Siricee** [comment]
你的博客是否是部署在了二级目录上？如果是的话可能造成静态资源路径找不到，解决方法请见 [这里](https://github.com/Siricee/hexo-theme-Chic/blob/master/README-CN.md#faq-提问)。

如果不是这个问题，请贴出你的工程目录和部署路径，我看看问题细节。

**Comment by dihambo** [comment]
![文档部署位置](https://user-images.githubusercontent.com/35786546/96086009-33df1880-0ef4-11eb-88e9-d899ea0abe42.png)
这个是我的部署位置

**Comment by dihambo** [comment]
哦对了，我还没有部署到服务器上，目前只是在本地服务器上测试和学习
