### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by hakcat** [Siricee/hexo-theme-Chic#94]
Hi developer,
how can I add a search engine to this theme?

Thanks

**Comment by Siricee** [comment]
Hi hakcat,
As the owner of chic, for functional considerations,I decided not to add the search engine to the theme as native suppout.
But I agree that other developers to implement this function on branches.

You can click the link below as reference.
[zgsxxzzyl/hexo-theme-Chic](https://github.com/zgsxxzzyl/hexo-theme-Chic)
This developer used `hexo-generator-search`. you can config search function for theme in '_config.yml'.
