### ISSUE TITLE
大佬你好, 无法正确解析latex数学公式中的"\&"咋整, 解析出来"\"就没有了

### ISSUE THREAD

**Issue by qpwlkq** [Siricee/hexo-theme-Chic#97]
网页上无法显示公式, 直接显示:
.......\left(x_{i} & [x_{j}\right).......](url)

但实际原文是:
.......\left(x_{i} \& x_{j}\right).......

[网页显示](https://sm.ms/image/4CjELibqx9Dtuyr)

**Comment by qpwlkq** [comment]
https://qpwlkq.github.io/2021/01/06/Codeforces-Good-Bye-2020-E-Apollo-versus-Pan对二进制的灵活运用/

**Comment by Baileyswu** [comment]
me 2

**Comment by Siricee** [comment]
呃 我不知道你想显示的是 `\&` 还是 `&`……

如果是 `&` 的话，你输入的应该是 `$ \\& $`，因为 markdown 会对斜杠转义一次变成`\&`，然后latex再把`\&`转义成 `&`。

如果是 `\&` 的话，你输入的应该是`$$ /\\\& $$`。同理 markdown 会先做字符转义，将 `/\` 转换为 `/` 再交给latex处理。

之前工作有些忙没回请见谅。

有更多问题欢迎在issue中讨论，祝你用 Chic 用得开心，新年快乐~觉得有帮助的话欢迎点个star支持下，谢谢！

**Comment by qpwlkq** [comment]
"\\&"对我的编译器直接报错....
我以后特意多加一个"\"吧 @😏, 已经可以了
麻烦了,请你吃🍗🌭🍟🍔🍕

**Comment by qpwlkq** [comment]
"\\\\&"对我的编译器直接报错....
我以后特意多加一个"\\"吧 @😏, 已经可以了
麻烦了,请你吃🍗🌭🍟🍔🍕
